### PR TITLE
fix: add vite 4 in peerDepends

### PR DESCRIPTION
**Pull request by rah-emil**

### CODE REVIEW

**Comment by rah-emil** [comment]
It's working for my project

**Comment by olfek** [comment]
Could you merge this please? @wheatjs 

I'm getting this error.

```
>> npm i -D vite-plugin-vue-type-imports

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: <PROJECT_NAME>@0.0.0
npm ERR! Found: vite@4.0.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from vite-plugin-vue-type-imports@0.2.4
npm ERR! node_modules/vite-plugin-vue-type-imports
npm ERR!   dev vite-plugin-vue-type-imports@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
...
```

**Comment by olfek** [comment]
Using the package mentioned here (https://github.com/wheatjs/vite-plugin-vue-type-imports/issues/46#issuecomment-1363705331) in the meantime, thanks @rah-emil ❣️

**Comment by wheatjs** [comment]
Thank you, I've been meaning to get to this. Will do a release soon

**Comment by Andreas-Halemba** [comment]
Will you create a version any time soon? or should we use @rah-emil s package instead?

**Comment by BBoehm** [comment]
@wheatjs any update on this? Merge has happened in March, but still no release

**Comment by danimalweb** [comment]
Pretty please?

**Comment by wheatjs** [comment]
Sorry for the delay, new version has been published.

**Pull request merged**
